using System.Collections.Generic;
using WordInEnglishPro.Application_Context;
using WordInEnglishPro.Model;

namespace WordInEnglishPro.Helpers
{
    public class InformationData
    {
        private Application_ContextDB _dbContext = new Application_ContextDB();

        public void WORDEN()
        {
            var words = new List<WordEN>
                {
                    new WordEN { IdEN = 1, MyWord = "HELLO" },
                    new WordEN { IdEN = 2, MyWord = "BELLOW" },
                    new WordEN { IdEN = 3, MyWord = "BEHIND" },
                    new WordEN { IdEN = 4, MyWord = "ABOBE" },
                    new WordEN { IdEN = 5, MyWord = "MYSELF" },
                    new WordEN { IdEN = 6, MyWord = "ITSELF" },
                    new WordEN { IdEN = 7, MyWord = "WHOSE" },
                    new WordEN { IdEN = 8, MyWord = "BEEN" },
                    new WordEN { IdEN = 9, MyWord = "ASK" },
                    new WordEN { IdEN = 10, MyWord = "PHONE" },
                    new WordEN { IdEN = 11, MyWord = "I MEAN" },
                    new WordEN { IdEN = 12, MyWord = "SECURE" },
                    new WordEN { IdEN = 13, MyWord = "BEHAVIOR" },
                    new WordEN { IdEN = 14, MyWord = "SENCE" },
                    new WordEN { IdEN = 15, MyWord = "EITHER" },
                    new WordEN { IdEN = 16, MyWord = "BEING" },
                    new WordEN { IdEN = 17, MyWord = "WITHIN" },
                    new WordEN { IdEN = 18, MyWord = "MIGHT" },
                    new WordEN { IdEN = 19, MyWord = "THESE" },
                    new WordEN { IdEN = 20, MyWord = "THOSE" },
                    new WordEN {   IdEN = 21   ,   MyWord =    "MEAL"    },
                    new WordEN  {   IdEN = 22   ,   MyWord =    "PART"    },
                    new WordEN  {   IdEN = 23   ,   MyWord =    "DEALER"  },
                    new WordEN  {   IdEN = 24   ,   MyWord =    "DEALT"   },
                    new WordEN  {   IdEN = 25   ,   MyWord =    "DEAL"    },
                    new WordEN  {   IdEN = 26   ,   MyWord =    "EQUALLY" },
                    new WordEN  {   IdEN = 27   ,   MyWord =    "EQUAL"   },
                    new WordEN  {   IdEN = 28   ,   MyWord =    "YEAH RIGHT"  },
                    new WordEN  {   IdEN = 29   ,   MyWord =    "SUCH"    },
                    new WordEN  {   IdEN = 30   ,   MyWord =    "BEING"   },
                    new WordEN  {   IdEN = 31   ,   MyWord =    "WHATEVER"    },
                    new WordEN  {   IdEN = 32   ,   MyWord =    "WHOEVER" },
                    new WordEN  {   IdEN = 33   ,   MyWord =    "ONVOKED" },
                    new WordEN  {   IdEN = 34   ,   MyWord =    "ENCHANCE"    },
                    new WordEN  {   IdEN = 35   ,   MyWord =    "BECOME"  },
                    new WordEN  {   IdEN = 36   ,   MyWord =    "UPTO"    },
                    new WordEN  {   IdEN = 37   ,   MyWord =    "BRUSH"   },
                    new WordEN  {   IdEN = 38   ,   MyWord =    "RELATES" },
                    new WordEN  {   IdEN = 39   ,   MyWord =    "FORWARD" },
                    new WordEN  {   IdEN = 40   ,   MyWord =    "FULLY"   },
                    new WordEN  {   IdEN = 41   ,   MyWord =    "FIST"    },
                    new WordEN  {   IdEN = 42   ,   MyWord =    "RETRIEVE"    },
                    new WordEN  {   IdEN = 43   ,   MyWord =    "TRACK"   },
                    new WordEN  {   IdEN = 44   ,   MyWord =    "NEVER"   },
                    new WordEN  {   IdEN = 45   ,   MyWord =    "NEVER MIND"  },
                    new WordEN  {   IdEN = 46   ,   MyWord =    "ME TOO"  },
                    new WordEN  {   IdEN = 47   ,   MyWord =    "SOMETHING"   },
                    new WordEN  {   IdEN = 48   ,   MyWord =    "WHEREVER"    },
                    new WordEN  {   IdEN = 49   ,   MyWord =    "DOES"    },
                    new WordEN  {   IdEN = 50   ,   MyWord =    "APPEAR"  },
                    new WordEN  {   IdEN = 51   ,   MyWord =    "APPEARANCE"  },
                    new WordEN  {   IdEN = 52   ,   MyWord =    "APPEARED"    },
                    new WordEN  {   IdEN = 53   ,   MyWord =    "APPEARS" },
                    new WordEN  {   IdEN = 54   ,   MyWord =    "APPEARING"   },
                    new WordEN  {   IdEN = 55   ,   MyWord =    "MATTER"  },
                    new WordEN  {   IdEN = 56   ,   MyWord =    "THEN"    },
                    new WordEN  {   IdEN = 57   ,   MyWord =    "THEM"    },
                    new WordEN  {   IdEN = 58   ,   MyWord =    "EXPLOIT" },
                    new WordEN  {   IdEN = 59   ,   MyWord =    "KEEN"    },
                    new WordEN  {   IdEN = 60   ,   MyWord =    "PORPOSE" },
                    new WordEN  {   IdEN = 61   ,   MyWord =    "WIDELY"  },
                    new WordEN  {   IdEN = 62   ,   MyWord =    "ONCE"    },
                    new WordEN  {   IdEN = 63   ,   MyWord =    "JUST TO CASE"    },
                    new WordEN  {   IdEN = 64   ,   MyWord =    "NOW THAT"    },
                    new WordEN  {   IdEN = 65   ,   MyWord =    "I GET IT "   },
                    new WordEN  {   IdEN = 66   ,   MyWord =    "ME NEITHER"  },
                    new WordEN  {   IdEN = 67   ,   MyWord =    "UNDERSTAND"  },
                    new WordEN  {   IdEN = 68   ,   MyWord =    "SHIRT"   },
                    new WordEN  {   IdEN = 69   ,   MyWord =    "HOWEVER" },
                    new WordEN  {   IdEN = 70   ,   MyWord =    "INVOKED" },
                    new WordEN  {   IdEN = 71   ,   MyWord =    "SIDE"    },
                    new WordEN  {   IdEN = 72   ,   MyWord =    "SURELY"  },
                    new WordEN  {   IdEN = 73   ,   MyWord =    "TARGET"  },
                    new WordEN  {   IdEN = 74   ,   MyWord =    "MOSTY"   },
                    new WordEN  {   IdEN = 75   ,   MyWord =    "INTENDED"    },
                    new WordEN  {   IdEN = 76   ,   MyWord =    "ENSURE"  },
                    new WordEN  {   IdEN = 77   ,   MyWord =    "OVER"    },
                    new WordEN  {   IdEN = 78   ,   MyWord =    "ALL OVER"    },
                    new WordEN  {   IdEN = 79   ,   MyWord =    "OVER THERE"  },
                    new WordEN  {   IdEN = 80   ,   MyWord =    "RIGHT OVER"  },
                    new WordEN  {   IdEN = 81   ,   MyWord =    "UP HERE" },
                    new WordEN  {   IdEN = 82   ,   MyWord =    "TODO"    },
                    new WordEN  {   IdEN = 83   ,   MyWord =    "TO THINK"    },
                    new WordEN  {   IdEN = 84   ,   MyWord =    "TO LOOK" },
                    new WordEN  {   IdEN = 85   ,   MyWord =    "TO TAKE" },
                    new WordEN  {   IdEN = 86   ,   MyWord =    "TO SAY"  },
                    new WordEN  {   IdEN = 87   ,   MyWord =    "TO KNOW" },
                    new WordEN  {   IdEN = 88   ,   MyWord =    "TO HAVE" },
                    new WordEN  {   IdEN = 89   ,   MyWord =    "HOW'S EVERTHING" },
                    new WordEN  {   IdEN = 90   ,   MyWord =    "EVERTHING"   },
                    new WordEN  {   IdEN = 91   ,   MyWord =    "HOW ARE YOU" },
                    new WordEN  {   IdEN = 92   ,   MyWord =    "NO BAD"  },
                    new WordEN  {   IdEN = 93   ,   MyWord =    "TAKE IT EASY"    },
                    new WordEN  {   IdEN = 94   ,   MyWord =    "HAVE A NICE DAY" },
                    new WordEN  {   IdEN = 95   ,   MyWord =    "HOW FAST"    },
                    new WordEN  {   IdEN = 96   ,   MyWord =    "HOW LATE"    },
                    new WordEN  {   IdEN = 97   ,   MyWord =    "HOW TALL"    },
                    new WordEN  {   IdEN = 98   ,   MyWord =    "HOW BIG" },
                    new WordEN  {   IdEN = 99   ,   MyWord =    "HOW SMALL"   },
                    new WordEN  {   IdEN = 100  ,   MyWord =    "DOWN THERE"  },
                    new WordEN  {   IdEN = 101  ,   MyWord =    "WHAT DO YOU" },
                    new WordEN  {   IdEN = 102  ,   MyWord =    "WANT TO YOU" },
                    new WordEN  {   IdEN = 103  ,   MyWord =    "SHOW"    },
                    new WordEN  {   IdEN = 104  ,   MyWord =    "PUT" },
                    new WordEN  {   IdEN = 105  ,   MyWord =    "SET" },
                    new WordEN  {   IdEN = 106  ,   MyWord =    "GET" },
                    new WordEN  {   IdEN = 107  ,   MyWord =    "USE" },
                    new WordEN  {   IdEN = 108  ,   MyWord =    "SENTENCE"    },
                    new WordEN  {   IdEN = 109  ,   MyWord =    "JUST "   },
                    new WordEN  {   IdEN = 110  ,   MyWord =    "WAY" },
                    new WordEN  {   IdEN = 111  ,   MyWord =    "ALSO"    },
                    new WordEN  {   IdEN = 112  ,   MyWord =    "THERE"   },
                    new WordEN  {   IdEN = 113  ,   MyWord =    "TO TRY"  },
                    new WordEN  {   IdEN = 114  ,   MyWord =    "TO GIVE" },
                    new WordEN  {   IdEN = 115  ,   MyWord =    "QUITE"   },
                    new WordEN  {   IdEN = 116  ,   MyWord =    "MUCH"    },
                    new WordEN  {   IdEN = 117  ,   MyWord =    "CALL"    },
                    new WordEN  {   IdEN = 118  ,   MyWord =    "MAYBE"   },
                    new WordEN  {   IdEN = 119  ,   MyWord =    "COME"    },
                    new WordEN  {   IdEN = 120  ,   MyWord =    "TELL"    },
                    new WordEN  {   IdEN = 121  ,   MyWord =    "BARELLY" },
                    new WordEN  {   IdEN = 122  ,   MyWord =    "NOTHING" },
                    new WordEN  {   IdEN = 123  ,   MyWord =    "LESS"    },
                    new WordEN  {   IdEN = 124  ,   MyWord =    "MORE"    },
                    new WordEN  {   IdEN = 125  ,   MyWord =    "VERY"    },
                    new WordEN  {   IdEN = 126  ,   MyWord =    "I DON'T" },
                    new WordEN  {   IdEN = 127  ,   MyWord =    "SHE DOESN'T" },
                    new WordEN  {   IdEN = 128  ,   MyWord =    "HE DOESN'T"  },
                    new WordEN  {   IdEN = 129  ,   MyWord =    "IT DOESN'T"  },
                    new WordEN  {   IdEN = 130  ,   MyWord =    "YOU DON'T"   },
                    new WordEN  {   IdEN = 131  ,   MyWord =    "WE DON'T"    },
                    new WordEN  {   IdEN = 132  ,   MyWord =    "THEY DON'T"  },
                    new WordEN  {   IdEN = 133  ,   MyWord =    "EVEN SO" },
                    new WordEN  {   IdEN = 134  ,   MyWord =    "EVEN IF" },
                    new WordEN  {   IdEN = 135  ,   MyWord =    "EVEN MORE"   },
                    new WordEN  {   IdEN = 136  ,   MyWord =    "EVEN LESS"   },
                    new WordEN  {   IdEN = 137  ,   MyWord =    "EVEN BETTER" },
                    new WordEN  {   IdEN = 138  ,   MyWord =    "EVEN WORSE"  },
                    new WordEN  {   IdEN = 139  ,   MyWord =    "EVEN NOW"    },
                    new WordEN  {   IdEN = 140  ,   MyWord =    "EVEN THOUGH" },
                    new WordEN  {   IdEN = 141  ,   MyWord =    "ENTRY"   },
                    new WordEN  {   IdEN = 142  ,   MyWord =    "OVERIDDE"    },
                    new WordEN  {   IdEN = 143  ,   MyWord =    "OVERIDDED"   },
                    new WordEN  {   IdEN = 144  ,   MyWord =    "CARE"    },
                    new WordEN  {   IdEN = 145  ,   MyWord =    "STUFF"   },
                    new WordEN  {   IdEN = 146  ,   MyWord =    "LET ME SEE"  },
                    new WordEN  {   IdEN = 147  ,   MyWord =    "TOUGH"   },
                    new WordEN  {   IdEN = 148  ,   MyWord =    "THOUGHT" },
                    new WordEN  {   IdEN = 149  ,   MyWord =    "THROUGH" },
                    new WordEN  {   IdEN = 150  ,   MyWord =    "THROUGHOUT"  },
                    new WordEN  {   IdEN = 151  ,   MyWord =    "REJE"    },
                    new WordEN  {   IdEN = 152  ,   MyWord =    "SOMEWHERE"   },
                    new WordEN  {   IdEN = 153  ,   MyWord =    "CLOSE"   },
                    new WordEN  {   IdEN = 154  ,   MyWord =    "SOMEBODY"    },
                    new WordEN  {   IdEN = 155  ,   MyWord =    "SOMEDAY" },
                    new WordEN  {   IdEN = 156  ,   MyWord =    "SOMEWHO" },
                    new WordEN  {   IdEN = 157  ,   MyWord =    "SOMEONE" },
                    new WordEN  {   IdEN = 158  ,   MyWord =    "SOMEPLACE"   },
                    new WordEN  {   IdEN = 159  ,   MyWord =    "SOMEWAY" },
                    new WordEN  {   IdEN = 160  ,   MyWord =    "AFTER"   },
                    new WordEN  {   IdEN = 161  ,   MyWord =    "UP" },
                    new WordEN  {   IdEN = 162  ,   MyWord =    "DOWN"    },
                    new WordEN  {   IdEN = 163  ,   MyWord =    "LEFT"    },
                    new WordEN  {   IdEN = 164  ,   MyWord =    "RIGHT"   },
                    new WordEN  {   IdEN = 165  ,   MyWord =    "WOULD"   },
                    new WordEN  {   IdEN = 166  ,   MyWord =    "BACKWARD"    },
                    new WordEN  {   IdEN = 167  ,   MyWord =    "SMOOTH"  },
                    new WordEN  {   IdEN = 168  ,   MyWord =    "APPROVE" },
                    new WordEN  {   IdEN = 169  ,   MyWord =    "ARCHIEVED"   },
                    new WordEN  {   IdEN = 170  ,   MyWord =    "COULD"   },
                    new WordEN  {   IdEN = 171  ,   MyWord =    "DOESN'T" },
                    new WordEN  {   IdEN = 172  ,   MyWord =    "DID" },
                    new WordEN  {   IdEN = 173  ,   MyWord =    "DID'T"   },
                    new WordEN  {   IdEN = 174  ,   MyWord =    "MADE UP" },
                    new WordEN  {   IdEN = 175  ,   MyWord =    "STANDALONE"  },
                    new WordEN  {   IdEN = 176  ,   MyWord =    "QUICKLY" },
                    new WordEN  {   IdEN = 177  ,   MyWord =    "BY MISTAKE"  },
                    new WordEN  {   IdEN = 178  ,   MyWord =    "MISTAKE" },
                    new WordEN  {   IdEN = 179  ,   MyWord =    "ISSUES"  },
                    new WordEN  {   IdEN = 180  ,   MyWord =    "SOMEWHAT"    },
                    new WordEN  {   IdEN = 181  ,   MyWord =    "FAST"    },
                    new WordEN  {   IdEN = 182  ,   MyWord =    "PICK UP" },
                    new WordEN  {   IdEN = 183  ,   MyWord =    "FUTHER"  },
                    new WordEN  {   IdEN = 184  ,   MyWord =    "AVOID"   },
                    new WordEN  {   IdEN = 185  ,   MyWord =    "DEEP"    },
                    new WordEN  {   IdEN = 186  ,   MyWord =    "BEIGH"   },
                    new WordEN  {   IdEN = 187  ,   MyWord =    "BOADCAST"    },
                    new WordEN  {   IdEN = 188  ,   MyWord =    "BOUNDARY"    },
                    new WordEN  {   IdEN = 189  ,   MyWord =    "EARLY"   },
                    new WordEN  {   IdEN = 190  ,   MyWord =    "MOUNT"   },
                    new WordEN  {   IdEN = 191  ,   MyWord =    "UNMOUNT" },
                    new WordEN  {   IdEN = 192  ,   MyWord =    "HANDLER" },
                    new WordEN  {   IdEN = 193  ,   MyWord =    "GO ON"   },
                    new WordEN  {   IdEN = 194  ,   MyWord =    "GO INSIDE"   },
                    new WordEN  {   IdEN = 195  ,   MyWord =    "FINALLY" },
                    new WordEN  {   IdEN = 196  ,   MyWord =    "MERGE"   },
                    new WordEN  {   IdEN = 197  ,   MyWord =    "ABILITY" },
                    new WordEN  {   IdEN = 198  ,   MyWord =    "FALL BACK"   },
                    new WordEN  {   IdEN = 199  ,   MyWord =    "SPEND"   },
                    new WordEN  {   IdEN = 200  ,   MyWord =    "BY CHANCE"   },
                    new WordEN  {   IdEN = 201  ,   MyWord =    "SHOULD"  },
                    new WordEN  {   IdEN = 202  ,   MyWord =    "BY ACCIDENT" },
                    new WordEN  {   IdEN = 203  ,   MyWord =    "BY TURNS"    },
                    new WordEN  {   IdEN = 204  ,   MyWord =    "GAINS"   },
                    new WordEN  {   IdEN = 205  ,   MyWord =    "ACCORDING TO"    },
                    new WordEN  {   IdEN = 206  ,   MyWord =    "AS A RESULT" },
                    new WordEN  {   IdEN = 207  ,   MyWord =    "BY THE WAY"  },
                    new WordEN  {   IdEN = 208  ,   MyWord =    "IN SPRITE OF"    },
                    new WordEN  {   IdEN = 209  ,   MyWord =    "JUST IN CASE"    },
                    new WordEN  {   IdEN = 210  ,   MyWord =    "SPEND TIME"  },
                    new WordEN  {   IdEN = 211  ,   MyWord =    "NESTED"  },
                    new WordEN  {   IdEN = 212  ,   MyWord =    "BING"    },
                    new WordEN  {   IdEN = 213  ,   MyWord =    "THROW"   },
                    new WordEN  {   IdEN = 214  ,   MyWord =    "ENFORCE" },
                    new WordEN  {   IdEN = 215  ,   MyWord =    "PLASING" },
                    new WordEN  {   IdEN = 216  ,   MyWord =    "LOOPS"   },
                    new WordEN  {   IdEN = 217  ,   MyWord =    "GOTTA GO"    },
                    new WordEN  {   IdEN = 218  ,   MyWord =    "GO THERE"    },
                    new WordEN  {   IdEN = 219  ,   MyWord =    "DURING"  },
                    new WordEN  {   IdEN = 220  ,   MyWord =    "TRADEOFF"    },
                    new WordEN  {   IdEN = 221  ,   MyWord =    "HARD"    },
                    new WordEN  {   IdEN = 222  ,   MyWord =    "CARRIES" },
                    new WordEN  {   IdEN = 223  ,   MyWord =    "WELL"    },
                    new WordEN  {   IdEN = 224  ,   MyWord =    "HOLIDAY" },
                    new WordEN  {   IdEN = 225  ,   MyWord =    "BATH"    },
                    new WordEN  {   IdEN = 226  ,   MyWord =    "USING"   },
                    new WordEN  {   IdEN = 227  ,   MyWord =    "HUG" },
                    new WordEN  {   IdEN = 228  ,   MyWord =    "HUGE"    },
                    new WordEN  {   IdEN = 229  ,   MyWord =    "SONG"    },
                    new WordEN  {   IdEN = 230  ,   MyWord =    "WHICH"   },
                    new WordEN  {   IdEN = 231  ,   MyWord =    "COST"    },
                    new WordEN  {   IdEN = 232  ,   MyWord =    "WAS" },
                    new WordEN  {   IdEN = 233  ,   MyWord =    "WENT"    },
                    new WordEN  {   IdEN = 234  ,   MyWord =    "WAS" },
                    new WordEN  {   IdEN = 235  ,   MyWord =    "WENT"    },
                    new WordEN  {   IdEN = 236  ,   MyWord =    "WHICH"   },
                    new WordEN  {   IdEN = 237  ,   MyWord =    "NET" },
                    new WordEN  {   IdEN = 238  ,   MyWord =    "THEN"    },
                    new WordEN  {   IdEN = 239  ,   MyWord =    "A FEW"   },
                    new WordEN  {   IdEN = 240  ,   MyWord =    "TWICE"   },
                    new WordEN  {   IdEN = 241  ,   MyWord =    "I THINK SO"  },
                    new WordEN  {   IdEN = 242  ,   MyWord =    "FIRE "   },
                    new WordEN  {   IdEN = 243  ,   MyWord =    "EXIT"    },
                    new WordEN  {   IdEN = 244  ,   MyWord =    "EVER"    },
                    new WordEN  {   IdEN = 245  ,   MyWord =    "EVERY"   },
                    new WordEN  {   IdEN = 246  ,   MyWord =    "AS"  },
                    new WordEN  {   IdEN = 247  ,   MyWord =    "SOME"    },
                    new WordEN  {   IdEN = 248  ,   MyWord =    "AT"  },
                    new WordEN  {   IdEN = 249  ,   MyWord =    "AT"  },
                    new WordEN  {   IdEN = 250  ,   MyWord =    "AT"  },
                    new WordEN  {   IdEN = 251  ,   MyWord =    "WHILE"   },
                    new WordEN  {   IdEN = 252  ,   MyWord =    "GO"  },
                    new WordEN  {   IdEN = 253  ,   MyWord =    "LEFT GO" },
                    new WordEN  {   IdEN = 254  ,   MyWord =    "GOING"   },
                    new WordEN  {   IdEN = 255  ,   MyWord =    "I WAS"   },
                    new WordEN  {   IdEN = 256  ,   MyWord =    "I WENT"  },
                    new WordEN  {   IdEN = 257  ,   MyWord =    "I ATE"   },
                    new WordEN  {   IdEN = 258  ,   MyWord =    "I COOK"  },
                    new WordEN  {   IdEN = 259  ,   MyWord =    "FEEL"    },
                    new WordEN  {   IdEN = 260  ,   MyWord =    "SAD" },
                    new WordEN  {   IdEN = 261  ,   MyWord =    "LONG TIME"   },
                    new WordEN  {   IdEN = 262  ,   MyWord =    "I DID"   },
                    new WordEN  {   IdEN = 263  ,   MyWord =    "I DO"    },
                    new WordEN  {   IdEN = 264  ,   MyWord =    "ANY" },
                    new WordEN  {   IdEN = 265  ,   MyWord =    "ANYWAY"  },
                    new WordEN  {   IdEN = 266  ,   MyWord =    "ANYMORE" },
                    new WordEN  {   IdEN = 267  ,   MyWord =    "ANYTIME" },
                    new WordEN  {   IdEN = 268  ,   MyWord =    "AFTER YOU"   },
                    new WordEN  {   IdEN = 269  ,   MyWord =    "AFTER"   },
                    new WordEN  {   IdEN = 270  ,   MyWord =    "BEFORE"  },
                    new WordEN  {   IdEN = 271  ,   MyWord =    "GET ON"  },
                    new WordEN  {   IdEN = 272  ,   MyWord =    "RIGHT NOW"   },
                    new WordEN  {   IdEN = 273  ,   MyWord =    "NOW" },
                    new WordEN  {   IdEN = 274  ,   MyWord =    "HERE"    },
                    new WordEN  {   IdEN = 275  ,   MyWord =    "I GUESS SO"  },
                    new WordEN  {   IdEN = 276  ,   MyWord =    "GET OUT" },
                    new WordEN  {   IdEN = 277  ,   MyWord =    "GET OFF" },
                    new WordEN  {   IdEN = 278  ,   MyWord =    "GET IN"  },
                    new WordEN  {   IdEN = 279  ,   MyWord =    "GET TO"  },
                    new WordEN  {   IdEN = 280  ,   MyWord =    "GET UP"  },
                    new WordEN  {   IdEN = 281  ,   MyWord =    "GET DOWN"    },
                    new WordEN  {   IdEN = 282  ,   MyWord =    "GET AWAY"    },
                    new WordEN  {   IdEN = 283  ,   MyWord =    "ENJOY"   },
                    new WordEN  {   IdEN = 284  ,   MyWord =    "ENOUGHT" },
                    new WordEN  {   IdEN = 285  ,   MyWord =    "MUSCLE" },
                    new WordEN  {   IdEN = 286  ,   MyWord =    "KNIFE"   },
                    new WordEN  {   IdEN = 287  ,   MyWord =    "KNEE"    },
                    new WordEN  {   IdEN = 288  ,   MyWord =    "JUST KIDDING"    },
                    new WordEN  {   IdEN = 289  ,   MyWord =    "I FEEL YOU"  },
                    new WordEN  {   IdEN = 290  ,   MyWord =    "HOLD ON" },
                    new WordEN  {   IdEN = 291  ,   MyWord =    "IN NO TIME"  },
                    new WordEN  {   IdEN = 292  ,   MyWord =    "SOON"    },
                    new WordEN  {   IdEN = 293  ,   MyWord =    "LIKE"    },
                    new WordEN  {   IdEN = 294  ,   MyWord =    "PLAY"    },
                    new WordEN  {   IdEN = 295  ,   MyWord =    "WEATHER" },
                    new WordEN  {   IdEN = 296  ,   MyWord =    "I CAN FEEL"  },
                    new WordEN  {   IdEN = 297  ,   MyWord =    "SO THAT" },
                    new WordEN  {   IdEN = 298  ,   MyWord =    "WHAT WRONG"  },
                    new WordEN  {   IdEN = 299  ,   MyWord =    "SO"  },
                    new WordEN  {   IdEN = 300  ,   MyWord =    "SO MANY" },
                    new WordEN  {   IdEN = 301  ,   MyWord =    "SO HOPE" },
                    new WordEN  {   IdEN = 302  ,   MyWord =    "SO MUCH" },
                    new WordEN  {   IdEN = 303  ,   MyWord =    "NOT SO FAST" },
                    new WordEN  {   IdEN = 304  ,   MyWord =    "SO BE IT"    },
                    new WordEN  {   IdEN = 305  ,   MyWord =    "WHEN"    },
                    new WordEN  {   IdEN = 306  ,   MyWord =    "HOW" },
                    new WordEN  {   IdEN = 307  ,   MyWord =    "TOO" },
                    new WordEN  {   IdEN = 308  ,   MyWord =    "FOLLOW"  },
                    new WordEN  {   IdEN = 309  ,   MyWord =    "CAN "    },
                    new WordEN  {   IdEN = 310  ,   MyWord =    "LIVE"    },
                    new WordEN  {   IdEN = 311  ,   MyWord =    "KEEP"    },
                    new WordEN  {   IdEN = 312  ,   MyWord =    "MOVE"    },
                    new WordEN  {   IdEN = 313  ,   MyWord =    "START"   },
                    new WordEN  {   IdEN = 314  ,   MyWord =    "BEGIN"   },
                    new WordEN  {   IdEN = 315  ,   MyWord =    "PLAYING" },
                    new WordEN  {   IdEN = 316  ,   MyWord =    "END" },
                    new WordEN  {   IdEN = 317  ,   MyWord =    "LETTER"  },
                    new WordEN  {   IdEN = 318  ,   MyWord =    "LYRICS"  },
                    new WordEN  {   IdEN = 319  ,   MyWord =    "GROUP"   },
                    new WordEN  {   IdEN = 320  ,   MyWord =    "LIST"    },
                    };

            _dbContext.WordsEN.AddRange(words);
            _dbContext.SaveChanges();
        }

        public void WORDES()
        {
            var words = new List<WordES>
            {
                    new WordES { IdES = 1, MyWord = "HOLA" },
                    new WordES { IdES = 2, MyWord = "ABAJO" },
                    new WordES { IdES = 3, MyWord = "DETRAS" },
                    new WordES { IdES = 4, MyWord = "ARRIBA" },
                    new WordES { IdES = 5, MyWord = "YO MISMO" },
                    new WordES { IdES = 6, MyWord = "SI MISMO" },
                    new WordES { IdES = 7, MyWord = "CUYO" },
                    new WordES { IdES = 8, MyWord = "ESTADO" },
                    new WordES { IdES = 9, MyWord = "PREGUNTAR" },
                    new WordES { IdES = 10, MyWord = "TELEFONO" },
                    new WordES { IdES = 11, MyWord = "QUIERO DECIR" },
                    new WordES { IdES = 12, MyWord = "SEGURO" },
                    new WordES { IdES = 13, MyWord = "COMPORTAMIENTO" },
                    new WordES { IdES = 14, MyWord = "SENTIDO" },
                    new WordES { IdES = 15, MyWord = "YA SEA" },
                    new WordES { IdES = 16, MyWord = "SIENDO" },
                    new WordES { IdES = 17, MyWord = "DENTRO" },
                    new WordES { IdES = 18, MyWord = "PUEDE QUE" },
                    new WordES { IdES = 19, MyWord = "ESTOS" },
                    new WordES { IdES = 20, MyWord = "ESOS" },
                    new WordES  {   IdES = 21,   MyWord = "COMER"},
                    new WordES  {   IdES = 22   ,   MyWord =    "PARTE"   },
                    new WordES  {   IdES = 23   ,   MyWord =    "DISTRIBUIDOR"    },
                    new WordES  {   IdES = 24   ,   MyWord =    "TRATADO" },
                    new WordES  {   IdES = 25   ,   MyWord =    "ACORDO"  },
                    new WordES  {   IdES = 26   ,   MyWord =    "IGUALMENTE"  },
                    new WordES  {   IdES = 27   ,   MyWord =    "IGUAL"   },
                    new WordES  {   IdES = 28   ,   MyWord =    "SI CLARO"    },
                    new WordES  {   IdES = 29   ,   MyWord =    "SOMEJANTE"   },
                    new WordES  {   IdES = 30   ,   MyWord =    "SER" },
                    new WordES  {   IdES = 31   ,   MyWord =    "LO QUE SEA"  },
                    new WordES  {   IdES = 32   ,   MyWord =    "QUIEN SEA"   },
                    new WordES  {   IdES = 33   ,   MyWord =    "OPUESTO" },
                    new WordES  {   IdES = 34   ,   MyWord =    "MEJORA"  },
                    new WordES  {   IdES = 35   ,   MyWord =    "CONVERTIRSER"    },
                    new WordES  {   IdES = 36   ,   MyWord =    "HASTA"   },
                    new WordES  {   IdES = 37   ,   MyWord =    "PINCEL"  },
                    new WordES  {   IdES = 38   ,   MyWord =    "SE RELACIONA"    },
                    new WordES  {   IdES = 39   ,   MyWord =    "REENVIAR"    },
                    new WordES  {   IdES = 40   ,   MyWord =    "COMPLETAMENTE"   },
                    new WordES  {   IdES = 41   ,   MyWord =    "PUÑO"    },
                    new WordES  {   IdES = 42   ,   MyWord =    "RECUPERAR"   },
                    new WordES  {   IdES = 43   ,   MyWord =    "PISTA"   },
                    new WordES  {   IdES = 44   ,   MyWord =    "NUNCA"   },
                    new WordES  {   IdES = 45   ,   MyWord =    "OLVIDALO"    },
                    new WordES  {   IdES = 46   ,   MyWord =    "YO TAMBIEN"  },
                    new WordES  {   IdES = 47   ,   MyWord =    "ALGO"    },
                    new WordES  {   IdES = 48   ,   MyWord =    "DONDE SEA"   },
                    new WordES  {   IdES = 49   ,   MyWord =    "LO HACE" },
                    new WordES  {   IdES = 50   ,   MyWord =    "APARECER"    },
                    new WordES  {   IdES = 51   ,   MyWord =    "APARIENCIA"  },
                    new WordES  {   IdES = 52   ,   MyWord =    "APARECIO"    },
                    new WordES  {   IdES = 53   ,   MyWord =    "APARECE" },
                    new WordES  {   IdES = 54   ,   MyWord =    "APARECIENDO" },
                    new WordES  {   IdES = 55   ,   MyWord =    "ASUNTO"  },
                    new WordES  {   IdES = 56   ,   MyWord =    "ENTONCES"    },
                    new WordES  {   IdES = 57   ,   MyWord =    "SUS" },
                    new WordES  {   IdES = 58   ,   MyWord =    "EXPLORAL"    },
                    new WordES  {   IdES = 59   ,   MyWord =    "AFINADO" },
                    new WordES  {   IdES = 60   ,   MyWord =    "PROPOSITO"   },
                    new WordES  {   IdES = 61   ,   MyWord =    "EXTENSAMENTE"    },
                    new WordES  {   IdES = 62   ,   MyWord =    "UNA VEZ" },
                    new WordES  {   IdES = 63   ,   MyWord =    "POR SI ACASO"    },
                    new WordES  {   IdES = 64   ,   MyWord =    "AHORA QUE"   },
                    new WordES  {   IdES = 65   ,   MyWord =    "ENTIENDO"    },
                    new WordES  {   IdES = 66   ,   MyWord =    "YO TAMPOCO"  },
                    new WordES  {   IdES = 67   ,   MyWord =    "ENTENDER"    },
                    new WordES  {   IdES = 68   ,   MyWord =    "CAMISA"  },
                    new WordES  {   IdES = 69   ,   MyWord =    "COMO SEA"    },
                    new WordES  {   IdES = 70   ,   MyWord =    "INVOCADO"    },
                    new WordES  {   IdES = 71   ,   MyWord =    "LADO"    },
                    new WordES  {   IdES = 72   ,   MyWord =    "SEGURAMENTE" },
                    new WordES  {   IdES = 73   ,   MyWord =    "OBJETIVO"    },
                    new WordES  {   IdES = 74   ,   MyWord =    "LA MAYORIA"  },
                    new WordES  {   IdES = 75   ,   MyWord =    "DESTINADO A" },
                    new WordES  {   IdES = 76   ,   MyWord =    "ASEGURAR"    },
                    new WordES  {   IdES = 77   ,   MyWord =    "ENCIMA"  },
                    new WordES  {   IdES = 78   ,   MyWord =    "POR TODAS PARTES"    },
                    new WordES  {   IdES = 79   ,   MyWord =    "POR ALLI"    },
                    new WordES  {   IdES = 80   ,   MyWord =    "JUSTO ALLI"  },
                    new WordES  {   IdES = 81   ,   MyWord =    "AQUÍ ARRIBA" },
                    new WordES  {   IdES = 82   ,   MyWord =    "HACER"   },
                    new WordES  {   IdES = 83   ,   MyWord =    "PENSAR"  },
                    new WordES  {   IdES = 84   ,   MyWord =    "MIRAR"   },
                    new WordES  {   IdES = 85   ,   MyWord =    "TOMAR"   },
                    new WordES  {   IdES = 86   ,   MyWord =    "DECIR"   },
                    new WordES  {   IdES = 87   ,   MyWord =    "SABER"   },
                    new WordES  {   IdES = 88   ,   MyWord =    "TENER"   },
                    new WordES  {   IdES = 89   ,   MyWord =    "COMO VA TODO"    },
                    new WordES  {   IdES = 90   ,   MyWord =    "TODO"    },
                    new WordES  {   IdES = 91   ,   MyWord =    "COMO ESTAS"  },
                    new WordES  {   IdES = 92   ,   MyWord =    "NO ESTA MAL" },
                    new WordES  {   IdES = 93   ,   MyWord =    "TOMALO CON CALMA"    },
                    new WordES  {   IdES = 94   ,   MyWord =    "TEN UN BUEN DIA" },
                    new WordES  {   IdES = 95   ,   MyWord =    "QUE TAN RAPIDO"  },
                    new WordES  {   IdES = 96   ,   MyWord =    "QUE TAN TARDE"   },
                    new WordES  {   IdES = 97   ,   MyWord =    "QUE TAN ALTO"    },
                    new WordES  {   IdES = 98   ,   MyWord =    "QUE TAN GRANDE"  },
                    new WordES  {   IdES = 99   ,   MyWord =    "QUE TAN PEQUEÑO" },
                    new WordES  {   IdES = 100  ,   MyWord =    "ALLI ABAJO"  },
                    new WordES  {   IdES = 101  ,   MyWord =    "QUE QUIERES HACER"   },
                    new WordES  {   IdES = 102  ,   MyWord =    "QUE QUIERES HACER"   },
                    new WordES  {   IdES = 103  ,   MyWord =    "MOSTRAR" },
                    new WordES  {   IdES = 104  ,   MyWord =    "PONER"   },
                    new WordES  {   IdES = 105  ,   MyWord =    "ESTABLESER"  },
                    new WordES  {   IdES = 106  ,   MyWord =    "OBTENER" },
                    new WordES  {   IdES = 107  ,   MyWord =    "USAR"    },
                    new WordES  {   IdES = 108  ,   MyWord =    "ORACION" },
                    new WordES  {   IdES = 109  ,   MyWord =    "SOLO"    },
                    new WordES  {   IdES = 110  ,   MyWord =    "MANERA"  },
                    new WordES  {   IdES = 111  ,   MyWord =    "TAMBIEN" },
                    new WordES  {   IdES = 112  ,   MyWord =    "ALLA"    },
                    new WordES  {   IdES = 113  ,   MyWord =    "INTENTAR"    },
                    new WordES  {   IdES = 114  ,   MyWord =    "DAR" },
                    new WordES  {   IdES = 115  ,   MyWord =    "BASTANTE"    },
                    new WordES  {   IdES = 116  ,   MyWord =    "MUCHO"   },
                    new WordES  {   IdES = 117  ,   MyWord =    "LLAMAR"  },
                    new WordES  {   IdES = 118  ,   MyWord =    "TALVEZ"  },
                    new WordES  {   IdES = 119  ,   MyWord =    "VINO"    },
                    new WordES  {   IdES = 120  ,   MyWord =    "DECIR"   },
                    new WordES  {   IdES = 121  ,   MyWord =    "APENAS"  },
                    new WordES  {   IdES = 122  ,   MyWord =    "NADA"    },
                    new WordES  {   IdES = 123  ,   MyWord =    "MENOS"   },
                    new WordES  {   IdES = 124  ,   MyWord =    "MAS" },
                    new WordES  {   IdES = 125  ,   MyWord =    "MUY" },
                    new WordES  {   IdES = 126  ,   MyWord =    "YO NO"   },
                    new WordES  {   IdES = 127  ,   MyWord =    "ELLA NO" },
                    new WordES  {   IdES = 128  ,   MyWord =    "EL NO "  },
                    new WordES  {   IdES = 129  ,   MyWord =    "ESO NO"  },
                    new WordES  {   IdES = 130  ,   MyWord =    "TU NO"   },
                    new WordES  {   IdES = 131  ,   MyWord =    "NOSOTRO NO"  },
                    new WordES  {   IdES = 132  ,   MyWord =    "ELLOS NO"    },
                    new WordES  {   IdES = 133  ,   MyWord =    "AUN ASI" },
                    new WordES  {   IdES = 134  ,   MyWord =    "INCLUSO SI"  },
                    new WordES  {   IdES = 135  ,   MyWord =    "AUN MAS" },
                    new WordES  {   IdES = 136  ,   MyWord =    "AUN MENOS"   },
                    new WordES  {   IdES = 137  ,   MyWord =    "AUN MEJOR"   },
                    new WordES  {   IdES = 138  ,   MyWord =    "AUN PEOR"    },
                    new WordES  {   IdES = 139  ,   MyWord =    "INCLUSO AHORA"   },
                    new WordES  {   IdES = 140  ,   MyWord =    "AUNQUE"  },
                    new WordES  {   IdES = 141  ,   MyWord =    "ENTRADA" },
                    new WordES  {   IdES = 142  ,   MyWord =    "ANULAR"  },
                    new WordES  {   IdES = 143  ,   MyWord =    "ANULANDO"    },
                    new WordES  {   IdES = 144  ,   MyWord =    "CUIDADO" },
                    new WordES  {   IdES = 145  ,   MyWord =    "COSAS"   },
                    new WordES  {   IdES = 146  ,   MyWord =    "DEJAME VER"  },
                    new WordES  {   IdES = 147  ,   MyWord =    "FUERTE"  },
                    new WordES  {   IdES = 148  ,   MyWord =    "A PESAR DE"  },
                    new WordES  {   IdES = 149  ,   MyWord =    "ATRAVEZ DE"  },
                    new WordES  {   IdES = 150  ,   MyWord =    "A LO LARGO DE" },
                    new WordES  {   IdES = 151  ,   MyWord =    "RECHAZO" },
                    new WordES  {   IdES = 152  ,   MyWord =    "EN ALGUNA PARTE" },
                    new WordES  {   IdES = 153  ,   MyWord =    "CERCA"   },
                    new WordES  {   IdES = 154  ,   MyWord =    "ALGUIEN" },
                    new WordES  {   IdES = 155  ,   MyWord =    "ALGUN DIA"   },
                    new WordES  {   IdES = 156  ,   MyWord =    "ALGUIEN" },
                    new WordES  {   IdES = 157  ,   MyWord =    "ALGO"    },
                    new WordES  {   IdES = 158  ,   MyWord =    "EN ALGUN LUGAR"  },
                    new WordES  {   IdES = 159  ,   MyWord =    "DE ALGUN MODO"   },
                    new WordES  {   IdES = 160  ,   MyWord =    "DESPUES" },
                    new WordES  {   IdES = 161  ,   MyWord =    "ARRIBA"  },
                    new WordES  {   IdES = 162  ,   MyWord =    "ABAJO"   },
                    new WordES  {   IdES = 163  ,   MyWord =    "IZQUIERDA"   },
                    new WordES  {   IdES = 164  ,   MyWord =    "DERECHA" },
                    new WordES  {   IdES = 165  ,   MyWord =    "HARIA"   },
                    new WordES  {   IdES = 166  ,   MyWord =    "ATRÁS"   },
                    new WordES  {   IdES = 167  ,   MyWord =    "SUAVE"   },
                    new WordES  {   IdES = 168  ,   MyWord =    "APROBAR" },
                    new WordES  {   IdES = 169  ,   MyWord =    "APROBANDO"   },
                    new WordES  {   IdES = 170  ,   MyWord =    "PODRIA"  },
                    new WordES  {   IdES = 171  ,   MyWord =    "NO LO HACE"  },
                    new WordES  {   IdES = 172  ,   MyWord =    "HIZO"    },
                    new WordES  {   IdES = 173  ,   MyWord =    "NO HIZO" },
                    new WordES  {   IdES = 174  ,   MyWord =    "ARREGLANDO"  },
                    new WordES  {   IdES = 175  ,   MyWord =    "SER UNICO"   },
                    new WordES  {   IdES = 176  ,   MyWord =    "RAPIDAMENTE" },
                    new WordES  {   IdES = 177  ,   MyWord =    "POR ERROR"   },
                    new WordES  {   IdES = 178  ,   MyWord =    "ERROR"   },
                    new WordES  {   IdES = 179  ,   MyWord =    "PROBLEMAS"   },
                    new WordES  {   IdES = 180  ,   MyWord =    "UN TANTO"    },
                    new WordES  {   IdES = 181  ,   MyWord =    "RAPIDO"  },
                    new WordES  {   IdES = 182  ,   MyWord =    "LEVANTAR"    },
                    new WordES  {   IdES = 183  ,   MyWord =    "MAS ALLA"    },
                    new WordES  {   IdES = 184  ,   MyWord =    "EVITAR"  },
                    new WordES  {   IdES = 185  ,   MyWord =    "PROFUNDO"    },
                    new WordES  {   IdES = 186  ,   MyWord =    "SIENDO"  },
                    new WordES  {   IdES = 187  ,   MyWord =    "TRANSMISION" },
                    new WordES  {   IdES = 188  ,   MyWord =    "PERIMETRO"   },
                    new WordES  {   IdES = 189  ,   MyWord =    "TEMPRANO"    },
                    new WordES  {   IdES = 190  ,   MyWord =    "MONTAR"  },
                    new WordES  {   IdES = 191  ,   MyWord =    "DESMONTAR"   },
                    new WordES  {   IdES = 192  ,   MyWord =    "MANIPULADOR" },
                    new WordES  {   IdES = 193  ,   MyWord =    "CONTINUA"    },
                    new WordES  {   IdES = 194  ,   MyWord =    "ENTRA"   },
                    new WordES  {   IdES = 195  ,   MyWord =    "FINALMENTE"  },
                    new WordES  {   IdES = 196  ,   MyWord =    "UNIR"    },
                    new WordES  {   IdES = 197  ,   MyWord =    "CAPACIDAD"   },
                    new WordES  {   IdES = 198  ,   MyWord =    "RETROCEDER"  },
                    new WordES  {   IdES = 199  ,   MyWord =    "GUSTAR"  },
                    new WordES  {   IdES = 200  ,   MyWord =    "POR CASUALIDAD"  },
                    new WordES  {   IdES = 201  ,   MyWord =    "DEBERIA" },
                    new WordES  {   IdES = 202  ,   MyWord =    "POR ACCIDENTE"   },
                    new WordES  {   IdES = 203  ,   MyWord =    "POR TURNO"   },
                    new WordES  {   IdES = 204  ,   MyWord =    "GANANCIAS"   },
                    new WordES  {   IdES = 205  ,   MyWord =    "DEACUERDO A" },
                    new WordES  {   IdES = 206  ,   MyWord =    "COMO RESULTADO"  },
                    new WordES  {   IdES = 207  ,   MyWord =    "POR CIERTO"  },
                    new WordES  {   IdES = 208  ,   MyWord =    "A PESAR DE"  },
                    new WordES  {   IdES = 209  ,   MyWord =    "POR SI ACASO"    },
                    new WordES  {   IdES = 210  ,   MyWord =    "PASAR TIEMPO"    },
                    new WordES  {   IdES = 211  ,   MyWord =    "ANIDADO" },
                    new WordES  {   IdES = 212  ,   MyWord =    "VINCULO	" },
                    new WordES  {   IdES = 213  ,   MyWord =    "LANZAR"  },
                    new WordES  {   IdES = 214  ,   MyWord =    "HACER CUMPLIR"   },
                    new WordES  {   IdES = 215  ,   MyWord =    "PLASMADO	"    },
                    new WordES  {   IdES = 216  ,   MyWord =    "BUCLES"  },
                    new WordES  {   IdES = 217  ,   MyWord =    "ME TENGO QUE IR" },
                    new WordES  {   IdES = 218  ,   MyWord =    "VE ALLA" },
                    new WordES  {   IdES = 219  ,   MyWord =    "DURANTE" },
                    new WordES  {   IdES = 220  ,   MyWord =    "COMPENSACION"    },
                    new WordES  {   IdES = 221  ,   MyWord =    "DURO"    },
                    new WordES  {   IdES = 222  ,   MyWord =    "LLEVA"   },
                    new WordES  {   IdES = 223  ,   MyWord =    "BIEN"    },
                    new WordES  {   IdES = 224  ,   MyWord =    "DIA FESTIVO" },
                    new WordES  {   IdES = 225  ,   MyWord =    "BAÑERA"  },
                    new WordES  {   IdES = 226  ,   MyWord =    "USANDO"  },
                    new WordES  {   IdES = 227  ,   MyWord =    "ABRAZO"  },
                    new WordES  {   IdES = 228  ,   MyWord =    "ENORME"  },
                    new WordES  {   IdES = 229  ,   MyWord =    "CANCION" },
                    new WordES  {   IdES = 230  ,   MyWord =    "QUE" },
                    new WordES  {   IdES = 231  ,   MyWord =    "COSTO"   },
                    new WordES  {   IdES = 232  ,   MyWord =    "ESTABA"  },
                    new WordES  {   IdES = 233  ,   MyWord =    "FUIMOS"  },
                    new WordES  {   IdES = 234  ,   MyWord =    "FUE" },
                    new WordES  {   IdES = 235  ,   MyWord =    "FUERON"  },
                    new WordES  {   IdES = 236  ,   MyWord =    "CUAL"    },
                    new WordES  {   IdES = 237  ,   MyWord =    "RED" },
                    new WordES  {   IdES = 238  ,   MyWord =    "DESPUES" },
                    new WordES  {   IdES = 239  ,   MyWord =    "UNOS MINUTOS"    },
                    new WordES  {   IdES = 240  ,   MyWord =    "DOS VECES"   },
                    new WordES  {   IdES = 241  ,   MyWord =    "PIENSO QUE SI"   },
                    new WordES  {   IdES = 242  ,   MyWord =    "FUEGO"   },
                    new WordES  {   IdES = 243  ,   MyWord =    "SALIDA"  },
                    new WordES  {   IdES = 244  ,   MyWord =    "ALGUNA VEZ"  },
                    new WordES  {   IdES = 245  ,   MyWord =    "CADA"    },
                    new WordES  {   IdES = 246  ,   MyWord =    "COMO"    },
                    new WordES  {   IdES = 247  ,   MyWord =    "ALGUNO"  },
                    new WordES  {   IdES = 248  ,   MyWord =    "EN"  },
                    new WordES  {   IdES = 249  ,   MyWord =    "A"   },
                    new WordES  {   IdES = 250  ,   MyWord =    "DE"  },
                    new WordES  {   IdES = 251  ,   MyWord =    "MIENTRAS"    },
                    new WordES  {   IdES = 252  ,   MyWord =    "IR"  },
                    new WordES  {   IdES = 253  ,   MyWord =    "VAMOS"   },
                    new WordES  {   IdES = 254  ,   MyWord =    "VOY" },
                    new WordES  {   IdES = 255  ,   MyWord =    "FUI" },
                    new WordES  {   IdES = 256  ,   MyWord =    "YO FUI"  },
                    new WordES  {   IdES = 257  ,   MyWord =    "YO COMI" },
                    new WordES  {   IdES = 258  ,   MyWord =    "YO COCINO"   },
                    new WordES  {   IdES = 259  ,   MyWord =    "SENTIR"  },
                    new WordES  {   IdES = 260  ,   MyWord =    "TRISTE"  },
                    new WordES  {   IdES = 261  ,   MyWord =    "LARGO TIEMPO"    },
                    new WordES  {   IdES = 262  ,   MyWord =    "YO HICE" },
                    new WordES  {   IdES = 263  ,   MyWord =    "YO HAGO" },
                    new WordES  {   IdES = 264  ,   MyWord =    "CUALQUIER"   },
                    new WordES  {   IdES = 265  ,   MyWord =    "COMO SEA"    },
                    new WordES  {   IdES = 266  ,   MyWord =    "NO MAS"  },
                    new WordES  {   IdES = 267  ,   MyWord =    "CUANDO SEA"  },
                    new WordES  {   IdES = 268  ,   MyWord =    "DESPUES DE USTED"    },
                    new WordES  {   IdES = 269  ,   MyWord =    "DESPUES" },
                    new WordES  {   IdES = 270  ,   MyWord =    "ANTES"   },
                    new WordES  {   IdES = 271  ,   MyWord =    "SUBIR"   },
                    new WordES  {   IdES = 272  ,   MyWord =    "JUSTO AHORA" },
                    new WordES  {   IdES = 273  ,   MyWord =    "AHORA"   },
                    new WordES  {   IdES = 274  ,   MyWord =    "AQUÍ"    },
                    new WordES  {   IdES = 275  ,   MyWord =    "ESO SUPONGO" },
                    new WordES  {   IdES = 276  ,   MyWord =    "SALIR"   },
                    new WordES  {   IdES = 277  ,   MyWord =    "BAJARSE" },
                    new WordES  {   IdES = 278  ,   MyWord =    "ENTRAR"  },
                    new WordES  {   IdES = 279  ,   MyWord =    "LLEGAR A"    },
                    new WordES  {   IdES = 280  ,   MyWord =    "LEVANTAR"    },
                    new WordES  {   IdES = 281  ,   MyWord =    "BAJAR"   },
                    new WordES  {   IdES = 282  ,   MyWord =    "ESCAPAR" },
                    new WordES  {   IdES = 283  ,   MyWord =    "DISFRUTAR"   },
                    new WordES  {   IdES = 284  ,   MyWord =    "SUFICIENTE"  },
                    new WordES  {   IdES = 285  ,   MyWord =    "MUSCULO" },
                    new WordES  {   IdES = 286  ,   MyWord =    "CUCHILLO"    },
                    new WordES  {   IdES = 287  ,   MyWord =    "RODILLA" },
                    new WordES  {   IdES = 288  ,   MyWord =    "SOLO BROMEO" },
                    new WordES  {   IdES = 289  ,   MyWord =    "TE ENTIENDO" },
                    new WordES  {   IdES = 290  ,   MyWord =    "ESPERA UN POCO"  },
                    new WordES  {   IdES = 291  ,   MyWord =    "MY PRONTO"   },
                    new WordES  {   IdES = 292  ,   MyWord =    "PRONTO"  },
                    new WordES  {   IdES = 293  ,   MyWord =    "ME GUSTA"    },
                    new WordES  {   IdES = 294  ,   MyWord =    "JUGAR"   },
                    new WordES  {   IdES = 295  ,   MyWord =    "CLIMA"   },
                    new WordES  {   IdES = 296  ,   MyWord =    "PUEDO SENTIR"    },
                    new WordES  {   IdES = 297  ,   MyWord =    "PARA QUE"    },
                    new WordES  {   IdES = 298  ,   MyWord =    "QUE PASA"    },
                    new WordES  {   IdES = 299  ,   MyWord =    "ENTONCES"    },
                    new WordES  {   IdES = 300  ,   MyWord =    "TANTO"   },
                    new WordES  {   IdES = 301  ,   MyWord =    "ESO ESPERO"  },
                    new WordES  {   IdES = 302  ,   MyWord =    "DEMACIADO"   },
                    new WordES  {   IdES = 303  ,   MyWord =    "NO TAN RAPIDO"   },
                    new WordES  {   IdES = 304  ,   MyWord =    "QUE ASI SEA" },
                    new WordES  {   IdES = 305  ,   MyWord =    "CUANDO"  },
                    new WordES  {   IdES = 306  ,   MyWord =    "COMO"    },
                    new WordES  {   IdES = 307  ,   MyWord =    "DEMACIADO"   },
                    new WordES  {   IdES = 308  ,   MyWord =    "SEGUIR"  },
                    new WordES  {   IdES = 309  ,   MyWord =    "PODER"   },
                    new WordES  {   IdES = 310  ,   MyWord =    "VIVIR"   },
                    new WordES  {   IdES = 311  ,   MyWord =    "MANTENER"    },
                    new WordES  {   IdES = 312  ,   MyWord =    "MOVER"   },
                    new WordES  {   IdES = 313  ,   MyWord =    "INICIAR" },
                    new WordES  {   IdES = 314  ,   MyWord =    "EMPEZAR" },
                    new WordES  {   IdES = 315  ,   MyWord =    "JUGANDO" },
                    new WordES  {   IdES = 316  ,   MyWord =    "FINAL"   },
                    new WordES  {   IdES = 317  ,   MyWord =    "LETRA"   },
                    new WordES  {   IdES = 318  ,   MyWord =    "LETRAS"  },
                    new WordES  {   IdES = 319  ,   MyWord =    "GRUPO"   },
                    new WordES  {   IdES = 320  ,   MyWord =    "LISTA"   },
                    };

            _dbContext.WordsES.AddRange(words);
            _dbContext.SaveChanges();
        }
    }
}